In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
netflix_search = pd.read_csv('datasets/netflix-report/CONTENT_INTERACTION/SearchHistory.csv', encoding='ISO-8859-1', index_col=0)

In [9]:
netflix_search

,Country Iso Code,Device,Is Kids,Query Typed,Displayed Name,Action,Section,Utc Timestamp
Profile Name,,,,,,,,
Coco,GB,iPad,0,sex ed,NaN,select,title_results,2023-07-15 20:51:59
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 1""",play,title_results,2023-07-15 20:20:21
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 8""",play,title_results,2023-07-15 20:19:07
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 7""",play,title_results,2023-07-15 20:18:39
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 6""",play,title_results,2023-07-15 20:18:00
...,...,...,...,...,...,...,...,...
Ð¤Ð¹Ð¶,GB,Streaming Stick,0,happy birthday,Project McÂ²: Happy Birthday to You!,select,NaN,NaN
Ð¤Ð¹Ð¶,GB,Streaming Stick,0,happy birthday,All Hail King Julien: Happy Birthday to You!,select,NaN,NaN
Ð¤Ð¹Ð¶,GB,Streaming Stick,0,happy birthday,NaN,select,NaN,NaN
Nicola,GB,Streaming Stick,0,fi,NaN,play,title_results,2021-08-03 16:37:18
Nicola,GB,Streaming Stick,0,fi,NaN,select,title_results,2021-08-03 16:37:06

In [13]:
search_coco = netflix_search.drop(['Ð¤Ð¹Ð¶',
                                   'Nicola', 
                                   'Emily',
                                   'Marcus',])
search_coco

,Country Iso Code,Device,Is Kids,Query Typed,Displayed Name,Action,Section,Utc Timestamp
Profile Name,,,,,,,,
Coco,GB,iPad,0,sex ed,NaN,select,title_results,2023-07-15 20:51:59
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 1""",play,title_results,2023-07-15 20:20:21
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 8""",play,title_results,2023-07-15 20:19:07
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 7""",play,title_results,2023-07-15 20:18:39
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 6""",play,title_results,2023-07-15 20:18:00
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 4""",play,title_results,2023-07-15 20:17:18
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 4""",play,title_results,2023-07-15 20:16:49
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 3""",play,title_results,2023-07-15 20:15:39
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 2""",play,title_results,2023-07-15 20:14:44
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 1""",play,title_results,2023-07-15 20:13:21
Coco,GB,iPad,0,sex ed,"Sex Education: Season 1: ""Episode 1""",play,title_results,2023-07-15 20:00:58
Coco,GB,iPad,0,sex ed,NaN,select,title_results,2023-07-15 20:00:54
Coco,GB,iPad,0,love island,"Perfect Match: Season 1: ""Love Is the End Game""",play,title_results,2023-07-15 19:48:57
Coco,GB,iPad,0,love island,NaN,select,title_results,2023-07-15 19:48:48
Coco,GB,Streaming Stick,0,too,NaN,play,title_results,2023-07-12 19:30:15
Coco,GB,Streaming Stick,0,too,NaN,select,title_results,2023-07-12 19:30:06

In [15]:
search_emily = netflix_search.drop(['Ð¤Ð¹Ð¶',
                                    'Marcus',
                                    'Nicola',
                                    'Coco',])
search_emily

,Country Iso Code,Device,Is Kids,Query Typed,Displayed Name,Action,Section,Utc Timestamp
Profile Name,,,,,,,,
Emily,GB,Streaming Stick,0,k,NaN,play,title_results,2023-08-24 21:08:44
Emily,GB,Streaming Stick,0,k,NaN,select,title_results,2023-08-24 21:08:41
Emily,GB,Streaming Stick,0,lu,NaN,play,title_results,2023-08-09 20:31:21
Emily,GB,Streaming Stick,0,lu,NaN,select,title_results,2023-08-09 20:31:13
Emily,GB,Streaming Stick,0,all,All The Bright Places,select,title_results,2023-08-09 20:30:58
...,...,...,...,...,...,...,...,...
Emily,GB,Streaming Stick,0,he,NaN,play,NaN,NaN
Emily,GB,Streaming Stick,0,he,NaN,play,NaN,NaN
Emily,GB,Streaming Stick,0,fu,NaN,select,NaN,NaN
Emily,GB,Streaming Stick,0,fu,NaN,select,NaN,NaN
Emily,GB,Streaming Stick,0,he,NaN,add,NaN,NaN

In [17]:
search_marcus = netflix_search.drop(['Emily',
                                     'Ð¤Ð¹Ð¶',
                                     'Nicola',
                                     'Coco',])
search_marcus

,Country Iso Code,Device,Is Kids,Query Typed,Displayed Name,Action,Section,Utc Timestamp
Profile Name,,,,,,,,
Marcus,GB,Streaming Stick,0,NaN,Don't Say a Word,select,prequery_results,2023-08-26 20:16:00
Marcus,GB,Streaming Stick,0,dont,Don't Say a Word,select,title_results,2023-08-26 19:32:38
Marcus,GB,Streaming Stick,0,lu,NaN,select,title_results,2023-08-22 21:35:53
Marcus,GB,Streaming Stick,0,ha,Happiness for Beginners,play,title_results,2023-08-13 16:39:22
Marcus,GB,Streaming Stick,0,ha,Happiness for Beginners,play,title_results,2023-08-13 15:47:28
...,...,...,...,...,...,...,...,...
Marcus,GB,Streaming Stick,0,mic,NaN,play,NaN,NaN
Marcus,GB,Streaming Stick,0,mic,NaN,play,NaN,NaN
Marcus,GB,Streaming Stick,0,mic,NaN,play,NaN,NaN
Marcus,GB,Streaming Stick,0,mic,NaN,play,NaN,NaN
Marcus,GB,Streaming Stick,0,mic,NaN,play,NaN,NaN

In [18]:
search_emily['Displayed Name'].unique()

array([nan, 'All The Bright Places', 'After', 'The Girl Next Door',
       'Friday Night Plan', 'Harry Potter and the Prisoner of Azkaban',
       'tick, tick...BOOM!', 'The SpongeBob Movie: Sponge on the Run',
       'The Social Network', 'If Anything Happens I Love You', '1922',
       'Sense and Sensibility', "Lady Chatterley's Lover",
       'The Danish Girl', 'The King',
       'Trust No One: The Hunt for the Crypto King',
       'Cryptopia: Bitcoin, Blockchains and the Future of the Internet',
       "Creating The Queen's Gambit", 'The Net', 'Little Women', 'United',
       'Enola Holmes 2', 'Bohemian Rhapsody', '12 Years a Slave',
       'The Quick and the Dead', 'Once Upon a Time in Hollywood',
       "Don't Look Up", 'All Quiet on the Western Front', 'The Courier',
       'The Imitation Game',
       'Battle of Dunkirk: From Disaster to Triumph', 'Dunkirk',
       'Good Will Hunting', 'Enola Holmes', 'Love & Friendship',
       "Michael Jackson's This Is It", 'Metal Lords',
       'My Chemical Romance: The Black Parade Is Dead!', 'The Package',
       'The Twilight Saga: New Moon', 'The Craft', 'Bleach',
       'One Piece Stampede', "Kuroko's Basketball: Last Game",
       'The Seven Deadly Sins the Movie: Prisoners of the Sky',
       'Jack and Jill', 'The Week Of', '50 First Dates', 'Blended',
       'Grown Ups', 'The Sleepover', 'Wild Child', 'It Chapter Two',
       "She's the Man", '7 Emotions', 'Hairspray', 'Murder Mystery',
       'Tattoo Fixers: Season 2: "Episode 1"',
       'Young Royals: Season 1: "Episode 1"', 'The Adam Project',
       'Bride of Chucky', 'Bo Burnham: Inside', 'Jarocin',
       'Rush: Beyond the Lighted Stage',
       'Justin Bieber: This is my World',
       'Heroes: Silence and Rock & Roll', 'Oasis: Supersonic',
       'Count Me In', 'Arctic Monkeys: Behind the Music',
       'School of Rock', 'David Attenborough: A Life on Our Planet',
       'The Great Hack', "Ferris Bueller's Day Off",
       'Miracle in Cell No. 7',
       'My Chemical Romance: Things That Make You Go mmmm!',
       'Gyllene Tider', 'Ready Player One', 'New York Minute',
       'Sherlock Holmes', 'Minions', 'The Kissing Booth', 'Slender Man',
       'Monster House', 'The Climb', 'Divergent', 'The Hunger Games'],
      dtype=object)

In [19]:
search_coco['Displayed Name'].unique()

array([nan, 'Sex Education: Season 1: "Episode 1"',
       'Sex Education: Season 1: "Episode 8"',
       'Sex Education: Season 1: "Episode 7"',
       'Sex Education: Season 1: "Episode 6"',
       'Sex Education: Season 1: "Episode 4"',
       'Sex Education: Season 1: "Episode 3"',
       'Sex Education: Season 1: "Episode 2"',
       'Perfect Match: Season 1: "Love Is the End Game"'], dtype=object)

In [20]:
search_marcus['Displayed Name'].unique()

array(["Don't Say a Word", nan, 'Happiness for Beginners',
       'Michael McIntyre: Showman', 'The Edge of Seventeen',
       'Before I Fall', "Finder's Fee", 'Good Will Hunting',
       "Jerry Seinfeld: I'm Telling You for the Last Time",
       'The Lincoln Lawyer: Season 1: "The Magic Bullet Redux"',
       'The Weekend Away', 'The Hunt', 'Dogtooth', 'Red Notice',
       'See You Yesterday', 'The Hunger Games: Mockingjay - Part 1',
       'Ode to Joy', 'Deepwater Horizon', 'Harriet', "That's My Boy",
       'Identity Thief', 'Naked', 'Sextuplets', 'Tammy', 'Black Panther',
       'Triple Frontier', 'Jerry Seinfeld: 23 Hours To Kill', 'Awake',
       'Polar', 'The Break', 'San Andreas', 'Life in a Year',
       'Life of Pi', 'Line of Duty', 'The Warrior', 'Red Dot',
       'Elon Musk: Bloomberg Risk Takers', 'The Meg',
       "Best Wishes, Warmest Regards: A Schitt's Creek Farewell",
       'The Song of Names',
       'Brave Blue World: Racing to Solve Our Water Crisis', 'Water',
       'The Social Dilemma', 'Kill the Messenger', 'The Chase',
       'The Warning', 'The Invisible Guest', 'Disturbia', 'Your Son',
       'Wrecked', 'TAU', 'Bloodline', 'The Invisible Guardian',
       'Clinical', 'The Invitation', 'Enough', 'The Call', 'I See You',
       'Rebirth', "I'm Thinking of Ending Things", 'Newness',
       'Hot Girls Wanted', 'The Sex Movie', 'The Week Of',
       'Ricky Gervais: Humanity', 'Jurassic World',
       'Jurassic World: Fallen Kingdom', '13TH', 'Coffee & Kareem',
       'Due Date', 'Kicking & Screaming', 'Oblivion', 'Hitch',
       'Neighbors', 'Outbreak', 'The Wrong Missy',
       'Jerry Seinfeld: Comedian', 'Terminator: Dark Fate',
       'Terminator Genisys', 'Save Me'], dtype=object)

In [22]:
search_sophie = netflix_search.drop(['Nicola',
                                     'Emily',
                                     'Marcus',
                                     'Coco'])
search_sophie

,Country Iso Code,Device,Is Kids,Query Typed,Displayed Name,Action,Section,Utc Timestamp
Profile Name,,,,,,,,
Ð¤Ð¹Ð¶,GB,iPad,0,ginny,NaN,select,title_results,2023-08-22 18:04:17
Ð¤Ð¹Ð¶,GB,iPad,0,"gil,ore",NaN,select,title_results,2023-08-15 17:52:38
Ð¤Ð¹Ð¶,GB,Streaming Stick,0,es,Escape Room,play,title_results,2023-08-15 15:40:03
Ð¤Ð¹Ð¶,GB,Streaming Stick,0,es,Escape Room,play,title_results,2023-08-15 15:23:32
Ð¤Ð¹Ð¶,GB,Streaming Stick,0,es,Escape Room,select,title_results,2023-08-15 15:23:15
...,...,...,...,...,...,...,...,...
Ð¤Ð¹Ð¶,GB,Streaming Stick,0,happy birthday,NaN,select,NaN,NaN
Ð¤Ð¹Ð¶,GB,Streaming Stick,0,happy birthday,Project McÂ²: Happy Birthday to You!,select,NaN,NaN
Ð¤Ð¹Ð¶,GB,Streaming Stick,0,happy birthday,Project McÂ²: Happy Birthday to You!,select,NaN,NaN
Ð¤Ð¹Ð¶,GB,Streaming Stick,0,happy birthday,All Hail King Julien: Happy Birthday to You!,select,NaN,NaN
Ð¤Ð¹Ð¶,GB,Streaming Stick,0,happy birthday,NaN,select,NaN,NaN

In [23]:
search_sophie['Displayed Name'].unique()

array([nan, 'Escape Room', 'Miraculous: Ladybug & Cat Noir, The Movie',
       '20th Century Girl', 'Green Snake', 'Bubble', 'Senior Year',
       'Pitch Perfect', 'Mamma Mia! Here We Go Again', 'Purple Hearts',
       'LOL', "He's All That", 'Red Notice', 'A Whisker Away',
       'Along for the Ride', 'The Half Of It', 'Naked', 'A Part of You',
       '#realityhigh', 'Confessions of an Invisible Girl',
       'Ackley Bridge: Series 1: "Episode 1"',
       'Ackley Bridge: Series 3: "Episode 1"', 'The Dirt', 'Ocean Waves',
       'Words Bubble Up Like Soda Pop',
       'To All the Boys: P.S. I Still Love You', 'Airplane Mode',
       'The Hunger Games: Mockingjay - Part 2',
       'Boo, Bitch: Limited Series: "Life\'s a Bitch and Then You Die"',
       'The Divergent Series: Allegiant - Part 1',
       'The Divergent Series: Insurgent', 'Falling for Christmas',
       'Delivery by Christmas', 'The Boss Baby: Christmas Bonus',
       'Angel Falls Christmas', "She's All That", 'Enola Holmes 2',
       'If Anything Happens I Love You', 'Clueless', 'Do Revenge',
       'The Do-Over', 'Jack and Jill', "You Don't Mess with the Zohan",
       'I Now Pronounce You Chuck and Larry', 'Grown Ups',
       'Just Go With It', 'Murder Mystery', 'Blended', 'Hairspray',
       "She's the Man", 'Headspace: Unwind Your Mind',
       'The Royal Treatment', 'Next Gen', 'Wild Child',
       'Girl in the Picture', 'Monster High: Boo York, Boo York',
       'Monster High: Freaky Fusion', 'Monster High', 'Amateur',
       'My Little Pony Equestria Girls: Legend of Everfree',
       'My Little Pony Equestria Girls: Rainbow Rocks',
       'You vs. Wild: Out Cold', 'Marmaduke',
       'Captain Underpants Epic Choice-o-Rama',
       'Carmen Sandiego: To Steal or Not to Steal', 'Divergent', 'Hop',
       'The Adventures of Sharkboy and Lavagirl', 'Sonic the Hedgehog',
       'Dora and the Lost City of Gold', 'The Speed Cubers',
       'Meet the Parents', 'Meet the Fockers',
       'The Hunger Games: Catching Fire', 'Spider-Man 3',
       'The Hunger Games: Mockingjay - Part 1', 'The Kissing Booth 3',
       'Shrek Forever After', 'To All the Boys Iâ\x80\x99ve Loved Before',
       'Shrek 2', 'Shrek', 'Shrek (Widescreen)', 'Moana', 'Ballerina',
       'Last Christmas', 'Santa Girl', "A Witches' Ball",
       'Trolls Holiday Special',
       'A Christmas Special: Miraculous: Tales of Ladybug & Cat Noir',
       'Let It Snow', 'The Kissing Booth', '48 Christmas Wishes',
       'Christmas Story', 'A Christmas Story', 'Jumanji: The Next Level',
       'The Tooth Fairy', 'The Wilding', 'Jumanji',
       'Jumanji: Welcome to the Jungle', 'Work It',
       'Harry Potter and the Chamber of Secrets', 'The Little Prince',
       'Bee Movie', 'Mulan', 'Radio Rebel', 'Zero Dark Thirty',
       'Wonder Woman', 'Legally Blonde', 'Hubie Halloween',
       'The Angry Birds Movie', 'The Princess Switch: Switched Again',
       'Cinderella', 'The Princess Switch', 'Another Cinderella Story',
       'A Cinderella Story: Once Upon a Song', 'DJ Cinderella',
       'A Cinderella Story', 'Back of the Net', 'Wish Dragon',
       'Naruto Shippuden the Movie: Blood Prison', 'School of Rock',
       'Thunder Force', 'Bratz: Babyz: The Movie', 'Mean Girls',
       'Barbie: A Mermaid Tale 2',
       'Percy Jackson & the Olympians: The Lightning Thief',
       'Tom and Jerry: The Movie', 'Scooby-Doo', 'Minions',
       'Bruno and Boots: Go Jump in the Pool', 'White Fang',
       'Dolphin Kick', 'Show Dogs', 'Tall Girl',
       'Dance Academy: The Comeback', 'You Can Tutu', 'KIDS',
       'Barbie of Swan Lake', 'Hotel Transylvania 2',
       "Free Rein: Valentine's Day",
       'Free Rein: The Twelve Neighs of Christmas',
       'Free Rein: Season 2: "Gaby"',
       'My Little Pony Equestria Girls: Rollercoaster of Friendship',
       'The Story of Minecraft',
       'Man vs. Wild with Bear Grylls and PM Modi',
       'Family Reunion: Part 1: "Remember When I Lost My Sister?"',
       'Family Reunion: Part 2: "Remember the G Club?"',
       "My Babysitter's a Vampire: The Movie",
       'Word Party: Happy Birthday',
       'Legend Quest: Happy Birthday to You!',
       'My Little Pony: Happy Birthday to You!',
       'Barbie: Happy Birthday to You!',
       'Miraculous: Ladybug & Cat Noir: Happy Birthday to You!',
       'PokÃ©mon: Happy Birthday to You!',
       'LEGO Ninjago: Masters of Spinjitzu: Happy Birthday to You!',
       'Project McÂ²: Happy Birthday to You!',
       'All Hail King Julien: Happy Birthday to You!', 'Happy Death Day',
       'Barney: Happy Birthday Barney!'], dtype=object)